guestfs: bringup: fix networking issue
When doing make bringup, virt-builder boots an image with network to be
able to install packages for image baseline creation. In order to have
network in the booted image, isc-dhcp-client needs to be installed in
the system. Currently, guestfs-tools (virt-builder provier) package in
Debian Testing (trixie) does not install it as runtime dependency. While
we report this to Debian, add isc-dhcp-client as package dependency to
solve the issue.

This was reported already in a previous Debian release:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775514

This can be replicated with make bringup or any of the following
virt-builder commands:
virt-builder fedora-27 --install qemu-guest-agent
[   3.2] Downloading: http://archive.libguestfs.org/builder/fedora-27.xz
[   3.7] Planning how to build this image
[   3.7] Uncompressing
[   5.3] Opening the new disk
libguestfs: warning: current user is not a member of the KVM group (group ID 994). This user cannot access /dev/kvm, so libguestfs may run very slowly. It is recommended that you 'chmod 0666 /dev/kvm' or add the current user to the KVM group (you might need to log out and log in again).
[  27.3] Setting a random seed
[  27.4] Installing packages: qemu-guest-agent
Error: Failed to synchronize cache for repo 'updates'
virt-builder: error: dnf -y install 'qemu-guest-agent': command exited with
an error

If reporting bugs, run virt-builder with debugging enabled and include the
complete output:

  virt-builder -v -x [...]

sudo virt-builder debian-12 --install sudo
[   0.7] Downloading: http://builder.libguestfs.org/debian-12.xz
[   1.0] Planning how to build this image
[   1.0] Uncompressing
[   2.9] Opening the new disk
[   6.3] Setting a random seed
virt-builder: warning: random seed could not be set for this type of guest
[   6.4] Installing packages: sudo
Ign:1 http://security.debian.org/debian-security bookworm-security InRelease
Ign:2 http://deb.debian.org/debian bookworm InRelease
Ign:3 http://deb.debian.org/debian bookworm-updates InRelease
Ign:1 http://security.debian.org/debian-security bookworm-security InRelease
Ign:2 http://deb.debian.org/debian bookworm InRelease
Ign:3 http://deb.debian.org/debian bookworm-updates InRelease
Ign:2 http://deb.debian.org/debian bookworm InRelease
Ign:1 http://security.debian.org/debian-security bookworm-security InRelease
Ign:3 http://deb.debian.org/debian bookworm-updates InRelease
Err:2 http://deb.debian.org/debian bookworm InRelease
  Temporary failure resolving 'deb.debian.org'
Err:1 http://security.debian.org/debian-security bookworm-security InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian bookworm-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/bookworm-security/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  sudo
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1889 kB of archives.
After this operation, 6199 kB of additional disk space will be used.
Ign:1 http://deb.debian.org/debian bookworm/main amd64 sudo amd64 1.9.13p3-1
Ign:1 http://deb.debian.org/debian bookworm/main amd64 sudo amd64 1.9.13p3-1
Ign:1 http://deb.debian.org/debian bookworm/main amd64 sudo amd64 1.9.13p3-1
Err:1 http://deb.debian.org/debian bookworm/main amd64 sudo amd64 1.9.13p3-1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/sudo/sudo_1.9.13p3-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
virt-builder: error:
      export DEBIAN_FRONTEND=noninteractive
      apt_opts='-q -y -o Dpkg::Options::=--force-confnew'
      apt-get $apt_opts update
      apt-get $apt_opts install 'sudo'
    : command exited with an error

If reporting bugs, run virt-builder with debugging enabled and include the
complete output:

  virt-builder -v -x [...]

Signed-off-by: Daniel Gomez <da.gomez@samsung.com>