gen_nodes: remove workflows_reboot_limit duplicate
Fixes ansible-lint --fix playbooks error:

ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "<unicode string>", line 3, column 1:
    kdevops_enable_guestfs: False
    ^ (line: 3)
found duplicate key "workflows_reboot_limit" with value "False"
(original value: "False")
  in "<unicode string>", line 20, column 1:
    workflows_reboot_limit: False
    ^ (line: 20)

To suppress this check see:
    https://yaml.dev/doc/ruamel.yaml/api/#Duplicate_keys

Fixes: 1c73c3a49e2d ("fstests_watchdog: fix console log rotation
handling")
Signed-off-by: Daniel Gomez <da.gomez@samsung.com>