bringup_guestfs: fix group permissions for disks
Ensure libvirt-qemu group permissions are set to qemu image disks when
on libvirt system uri.

Permissions before:
namei --long /var/lib/libvirt/images/kdevops/guestfs/debian13/extra0.raw

f: /var/lib/libvirt/images/kdevops/guestfs/debian13/extra0.raw
drwxr-xr-x root    root         /
drwxr-xr-x root    root         var
drwxr-xr-x root    root         lib
drwxr-xr-x root    libvirt-qemu libvirt
drwxrwxr-x root    libvirt-qemu images
drwxrwxr-x root    libvirt-qemu kdevops
drwxrwxr-x root    libvirt-qemu guestfs
drwxrwxr-x dagomez dagomez      debian13
-rw-rw-r-- dagomez dagomez      extra0.raw

Permissions after:

f: /var/lib/libvirt/images/kdevops/guestfs/debian13/extra0.raw
drwxr-xr-x root    root         /
drwxr-xr-x root    root         var
drwxr-xr-x root    root         lib
drwxr-xr-x root    libvirt-qemu libvirt
drwxrwsr-x root    libvirt-qemu images
drwxrwsr-x root    libvirt-qemu kdevops
drwxrwsr-x root    libvirt-qemu guestfs
drwxrwsr-x dagomez libvirt-qemu debian13
-rw-rw-r-- dagomez libvirt-qemu extra0.raw

libvirt permission error:

make bringup
{...}
.//scripts/bringup_guestfs.sh
User dagomez is part of the libvirt-qemu group.
[   0.0] Examining the guest ...
{...}
[   5.1] SELinux relabelling
[   5.1] Performing "lvm-uuids" ...
Formatting '/var/lib/libvirt/images/kdevops/guestfs/debian13/extra0.raw',
fmt=raw size=107374182400
Formatting '/var/lib/libvirt/images/kdevops/guestfs/debian13/extra1.raw',
fmt=raw size=107374182400
Formatting '/var/lib/libvirt/images/kdevops/guestfs/debian13/extra2.raw',
fmt=raw size=107374182400
Formatting '/var/lib/libvirt/images/kdevops/guestfs/debian13/extra3.raw',
fmt=raw size=107374182400
Domain 'debian13' defined from .//guestfs/debian13/debian13.xml

error: Failed to start domain 'debian13'
error: internal error: QEMU unexpectedly closed the monitor
(vm='debian13'): 2025-04-23T14:17:23.707308Z qemu-system-x86_64: -device
virtio-blk-pci,drive=drv0,id=virtio-drv0,serial=kdevops0,bus=
pcie-port-for-virtio-0,addr=0x0,iothread=kdevops-virtio-iothread-0,
logical_block_size=512,physical_block_size=512: Could not open
'/var/lib/libvirt/images/kdevops/guestfs/debian13/extra0.raw':
Permission denied

Failed to start debian13
make: *** [scripts/guestfs.Makefile:80: bringup_guestfs] Error 1

Signed-off-by: Daniel Gomez <da.gomez@samsung.com>